services:
  checkout:
    image: t-checkout-qa:latest
    container_name: checkout_container_qa
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - NEXT_PUBLIC_JWT_SECRET=${NEXT_PUBLIC_JWT_SECRET}
      - NEXT_PUBLIC_BASE_URL_QA=${NEXT_PUBLIC_BASE_URL_QA}
      - NEXT_PUBLIC_QA=${NEXT_PUBLIC_QA}
    ports:
      - 3000:3000
    networks:
      - checkout-network

networks:
  checkout-network:
    name: nginx-proxy-manager_default
    external: true