name: dev ci

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy_dev:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Hostinger Deploy
        uses: appleboy/scp-action@v0.1.7
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ".,!.env,"
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          port: ${{ secrets.REMOTE_PORT }}
          target: ${{ secrets.TARGET }}
            
      
      - name: Build docker
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          port: ${{ secrets.REMOTE_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /system/dev/checkout
            echo "NEXT_PUBLIC_BASE_URL_QA=${{secrets.NEXT_PUBLIC_BASE_URL_QA}}" >> .env
            echo "NEXT_PUBLIC_QA=${{secrets.NEXT_PUBLIC_QA}}" >> .env
            echo "NEXT_PUBLIC_JWT_SECRET=${{secrets.NEXT_PUBLIC_JWT_SECRET}}" >> .env
            docker stop 'checkout_container_qa'
            docker rm 'checkout_container_qa'
            docker compose -f docker-compose-qa.yml -p jibot-checkout-qa up -d
